### ISSUE TITLE
十月规划和进度安排

### ISSUE THREAD

**Issue by SimplyY** [SimplyY/JnPlants#28]
# 十月总规划

2015.10.7
### web：
1. 美景展示
2. 投稿页面（美景、植物）。
3. 植物数据系统。
### 安卓：
1. QQ第三方登录并获取账号信息 。
2. 主页ListVIew美景内容的获取。
3. 搜索植物功能。
4. 个人页面
### 林超组：
1. 联系基建处，拿到植物信息，美景图片（急）。 
2. 对已经采集好的数据整理分析。
3. 拍照功能。
### 王莉组
1. 一周内报销好所有发票。
2. 做好美景和单个植物的markdown例子。(压缩照片)
3. 协助林超整理数据，并使用其在投稿页面投稿。
4. 联系班主任关于“材料费”的消费。
5. 写到年底的总计划。
## 注意：

 今晚6:30开会，记得把所有发票带过去。
## 十一月计划
- 通知功能（list 安卓，点击item webview ）
- 搜索植物功能
- 机器学习。
## 需求
#33  地图功能要不要

**Comment by fujian-zfj** [comment]
## android
- [x] QQ第三方登录，获取账号信息并存入本地数据库
- [ ] 主页ListVIew美景内容的获取

### 已完成

> 1 将获取的QQ头像，昵称保存到本地
> 2 获取存储到本地的QQ头像，即当按下back键退出活动（onDestroy（））时，再次进入应用不必重新从网络上获取QQ头像，直接先判断本地是否有头像，若有，则直接获取。
> 3 个人信息页面，获取本地数据库的用户头像和昵称并显示，右滑或是按下返回按钮退出个人页面
> 4 主页ListView美景内容获取成功，并将图片的棱角圆角化，点击item后进入相应的美景页面。

### 下一步

  将美景图片信息存储到本地数据库中

### TODO
- [x] 数据库实现(第一步先储存个人信息，以后还要储存收藏美景，美景list，收藏植物等)
- [x] 发送http请求 学习资料：https://github.com/SimplyY/JnPlants/issues/18 ，接收response回来的数据(用户信息、美景 list 等)。
- [x] 首页(功能按钮来切换到其他activity，美景list，点击进入webview)

**Comment by IwilsOday** [comment]
## web

> 10.25

### 完成
- [x] 美景投稿页面 基本完成  #27
- [x] 服务器端 数据库表建立和 restful 化：用户、评论、美景、植物
- [x] 单个美景页面上线

**Comment by putiwangsheng** [comment]
## UI

> 2015.10.28

### 正在：
- 单个美景页面 

### 已完成：logo

![logo](https://cloud.githubusercontent.com/assets/8708202/10777933/8caf2f66-7d5b-11e5-8178-955ee1b575ab.png)
美景list图片
![147ba54-652d-11e5-979b-fbd6f9d67e4e](https://cloud.githubusercontent.com/assets/8708202/10843431/fc20f3d2-7f33-11e5-9269-a9565fecb415.png)

### 即将：

评论页面

**Comment by IwilsOday** [comment]
## 王莉组

> 2015.10.17

### 正在：
- 报销 #29  
- 今天下午拿到了林超的照片,还未处理完
- 图标素材已经找好了

### 即将：
- 继续处理照片
- 继续咨询"内存条"
- 将图标P出来

**Comment by littletomato** [comment]
## 林超组

> 10.10

### 正在
- [ ] 数据资料的收集
- [ ] 图像特征值的提取

### 即将
1. 打电话给基建处老师，那边说要到这周二才有时间
2. 图像特征的提取

### 已完成
1. 通过多途径收集所需美景照片（搜寻qq空间），同时联系了基建处方面，取得了他们的同意，获得了美景图片。同时对图片进行裁剪，压缩，分类等基础图片处理工作
2. 初步学习了图像识别方面的知识，目前已经完成了图像的灰度化，以及尝试了多种图像分割的算法等图像预处理工作
